### ISSUE TITLE
Address component types parsed as single string

### ISSUE THREAD

**Issue by steventebrinke** [mcross1882/geocoder#12]
The types of an address component is a `Seq[String]`, but in my test responses it looks like `List("politicalsublocalitysublocality_level_1")`. I assume this is a bug and should be: `List("political", "sublocality", "sublocality_level_1")`.

**Comment by mcross1991** [comment]
Sorry I'm a bit confused by the issue here. Are you trying to use the `lookup(components: Seq[AbstractComponent])` method? If you could post some sample code that would help a lot!

Thanks for reporting,
Matt

**Comment by steventebrinke** [comment]
Sorry for being unclear, here some example code, with as comments the result I would expect:
```scala
val results = Geocoder.create.lookup("Leidseweg 90, Utrecht, NL")
val component = results.head.addressComponents.filter(_.shortName == "UT").head
println(component)
println(component.types.length) // Expected: 2
println(component.types) // Expected: List(administrative_area_level_1, political)
```
The request is the following: https://maps.googleapis.com/maps/api/geocode/json?address=Leidseweg%2090,%20Utrecht,%20NL
