### ISSUE TITLE
Lookup without results fails

### ISSUE THREAD

**Issue by steventebrinke** [mcross1882/geocoder#15]
When a lookup provides no results (status is ZERO_RESULTS) a generic exception is thrown. IMO, the class `Response` should contain the following code:
```scala
val success: Boolean = status == "OK" || status == "ZERO_RESULTS"
```

When you look at `sendRequest`, the current implementation makes no sense without the above fix. In short, the implementation is as follows:
```scala
if (!response.success) { // if (status != "OK")
    throw new InvalidLocationException()
}
if (response.hasNoResults) { // if (status == "ZERO_RESULTS")
    Seq.empty[Result] // Unreachable code, since an exception was already thrown
}
```

**Comment by mcross1991** [comment]
Very good find @steventebrinke I've gone ahead and opened a PR for this which will probably be launched some point over the weekend as a minor point release.
