### ISSUE TITLE
Add response status to InvalidLocationException

### ISSUE THREAD

**Issue by steventebrinke** [mcross1882/geocoder#18]
Each response has a status. It would be nice to also add this status to the InvalidLocationException, to allow distinguishing what caused the exception. (E.g.: reaching my request quota should be handled differently from specifying an invalid query.)

**Comment by mcross1991** [comment]
Great point! This has been on my roadmap for awhile -- improving the exceptions. I will try to get something out before the holidays on this front 👍 

Cheers
